// Copyright 2024 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: datax.proto

package datax

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// unique name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"primary_key"`
	// tag name from StructTag
	TagName string `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty" toml:"tag_name,omitempty" yaml:"tag_name,omitempty"`
	// value type
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty"`
	// struct defines url, ex: github.com/lynkdb/lynkx/datax.ServiceInstance
	Kind string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Attrs []string `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty" toml:"attrs,omitempty" yaml:"attrs,omitempty"`
	Enums []string `protobuf:"bytes,7,rep,name=enums,proto3" json:"enums,omitempty" toml:"enums,omitempty" yaml:"enums,omitempty"`
	Opts map[string]*structpb.Value `protobuf:"bytes,8,rep,name=opts,proto3" json:"opts,omitempty" toml:"opts,omitempty" yaml:"opts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Fields []*SpecField `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	// description
	Desc string `protobuf:"bytes,10,opt,name=desc,proto3" json:"desc,omitempty" toml:"desc,omitempty" yaml:"desc,omitempty"`
}

func (x *SpecField) Reset() {
	*x = SpecField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecField) ProtoMessage() {}

func (x *SpecField) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecField.ProtoReflect.Descriptor instead.
func (*SpecField) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{0}
}

func (x *SpecField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecField) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *SpecField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SpecField) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SpecField) GetAttrs() []string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *SpecField) GetEnums() []string {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *SpecField) GetOpts() map[string]*structpb.Value {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *SpecField) GetFields() []*SpecField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SpecField) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string       `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name   string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Fields []*SpecField `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetFields() []*SpecField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ServiceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty" toml:"code,omitempty" yaml:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" toml:"message,omitempty" yaml:"message,omitempty"`
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServiceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	RequestSpec  *Spec  `protobuf:"bytes,4,opt,name=request_spec,json=requestSpec,proto3" json:"request_spec,omitempty" toml:"request_spec,omitempty" yaml:"request_spec,omitempty"`
	ResponseSpec *Spec  `protobuf:"bytes,6,opt,name=response_spec,json=responseSpec,proto3" json:"response_spec,omitempty" toml:"response_spec,omitempty" yaml:"response_spec,omitempty"`
}

func (x *ServiceMethod) Reset() {
	*x = ServiceMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMethod) ProtoMessage() {}

func (x *ServiceMethod) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMethod.ProtoReflect.Descriptor instead.
func (*ServiceMethod) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMethod) GetRequestSpec() *Spec {
	if x != nil {
		return x.RequestSpec
	}
	return nil
}

func (x *ServiceMethod) GetResponseSpec() *Spec {
	if x != nil {
		return x.ResponseSpec
	}
	return nil
}

type ServiceInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Methods []*ServiceMethod `protobuf:"bytes,9,rep,name=methods,proto3" json:"methods,omitempty" toml:"methods,omitempty" yaml:"methods,omitempty"`
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInstance) GetMethods() []*ServiceMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ApiListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiListRequest) Reset() {
	*x = ApiListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListRequest) ProtoMessage() {}

func (x *ApiListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListRequest.ProtoReflect.Descriptor instead.
func (*ApiListRequest) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{5}
}

type ApiListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string             `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status   *ServiceStatus     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Services []*ServiceInstance `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" toml:"services,omitempty" yaml:"services,omitempty"`
}

func (x *ApiListResponse) Reset() {
	*x = ApiListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListResponse) ProtoMessage() {}

func (x *ApiListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListResponse.ProtoReflect.Descriptor instead.
func (*ApiListResponse) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{6}
}

func (x *ApiListResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiListResponse) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ApiListResponse) GetServices() []*ServiceInstance {
	if x != nil {
		return x.Services
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string           `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" toml:"service_name,omitempty" yaml:"service_name,omitempty"`
	MethodName  string           `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty" toml:"method_name,omitempty" yaml:"method_name,omitempty"`
	Data        *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{7}
}

func (x *Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Request) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *Request) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string           `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status *ServiceStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Data   *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Response) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_datax_proto protoreflect.FileDescriptor

var file_datax_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe7, 0x02, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x12, 0x3b, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x78, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x4f, 0x70,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x35, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x78, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x1a, 0x4f, 0x0a, 0x09, 0x4f, 0x70, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x65, 0x0a, 0x04, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x9f, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x79,
	0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x22, 0x62, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x41, 0x70, 0x69, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x78, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x32, 0xa9, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x54, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12,
	0x1b, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x78, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x48, 0x03,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_datax_proto_rawDescOnce sync.Once
	file_datax_proto_rawDescData = file_datax_proto_rawDesc
)

func file_datax_proto_rawDescGZIP() []byte {
	file_datax_proto_rawDescOnce.Do(func() {
		file_datax_proto_rawDescData = protoimpl.X.CompressGZIP(file_datax_proto_rawDescData)
	})
	return file_datax_proto_rawDescData
}

var file_datax_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_datax_proto_goTypes = []interface{}{
	(*SpecField)(nil),       // 0: lynkdb.lynkx.datax.SpecField
	(*Spec)(nil),            // 1: lynkdb.lynkx.datax.Spec
	(*ServiceStatus)(nil),   // 2: lynkdb.lynkx.datax.ServiceStatus
	(*ServiceMethod)(nil),   // 3: lynkdb.lynkx.datax.ServiceMethod
	(*ServiceInstance)(nil), // 4: lynkdb.lynkx.datax.ServiceInstance
	(*ApiListRequest)(nil),  // 5: lynkdb.lynkx.datax.ApiListRequest
	(*ApiListResponse)(nil), // 6: lynkdb.lynkx.datax.ApiListResponse
	(*Request)(nil),         // 7: lynkdb.lynkx.datax.Request
	(*Response)(nil),        // 8: lynkdb.lynkx.datax.Response
	nil,                     // 9: lynkdb.lynkx.datax.SpecField.OptsEntry
	(*structpb.Struct)(nil), // 10: google.protobuf.Struct
	(*structpb.Value)(nil),  // 11: google.protobuf.Value
}
var file_datax_proto_depIdxs = []int32{
	9,  // 0: lynkdb.lynkx.datax.SpecField.opts:type_name -> lynkdb.lynkx.datax.SpecField.OptsEntry
	0,  // 1: lynkdb.lynkx.datax.SpecField.fields:type_name -> lynkdb.lynkx.datax.SpecField
	0,  // 2: lynkdb.lynkx.datax.Spec.fields:type_name -> lynkdb.lynkx.datax.SpecField
	1,  // 3: lynkdb.lynkx.datax.ServiceMethod.request_spec:type_name -> lynkdb.lynkx.datax.Spec
	1,  // 4: lynkdb.lynkx.datax.ServiceMethod.response_spec:type_name -> lynkdb.lynkx.datax.Spec
	3,  // 5: lynkdb.lynkx.datax.ServiceInstance.methods:type_name -> lynkdb.lynkx.datax.ServiceMethod
	2,  // 6: lynkdb.lynkx.datax.ApiListResponse.status:type_name -> lynkdb.lynkx.datax.ServiceStatus
	4,  // 7: lynkdb.lynkx.datax.ApiListResponse.services:type_name -> lynkdb.lynkx.datax.ServiceInstance
	10, // 8: lynkdb.lynkx.datax.Request.data:type_name -> google.protobuf.Struct
	2,  // 9: lynkdb.lynkx.datax.Response.status:type_name -> lynkdb.lynkx.datax.ServiceStatus
	10, // 10: lynkdb.lynkx.datax.Response.data:type_name -> google.protobuf.Struct
	11, // 11: lynkdb.lynkx.datax.SpecField.OptsEntry.value:type_name -> google.protobuf.Value
	5,  // 12: lynkdb.lynkx.datax.DataxService.ApiList:input_type -> lynkdb.lynkx.datax.ApiListRequest
	7,  // 13: lynkdb.lynkx.datax.DataxService.Exec:input_type -> lynkdb.lynkx.datax.Request
	6,  // 14: lynkdb.lynkx.datax.DataxService.ApiList:output_type -> lynkdb.lynkx.datax.ApiListResponse
	8,  // 15: lynkdb.lynkx.datax.DataxService.Exec:output_type -> lynkdb.lynkx.datax.Response
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_datax_proto_init() }
func file_datax_proto_init() {
	if File_datax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datax_proto_goTypes,
		DependencyIndexes: file_datax_proto_depIdxs,
		MessageInfos:      file_datax_proto_msgTypes,
	}.Build()
	File_datax_proto = out.File
	file_datax_proto_rawDesc = nil
	file_datax_proto_goTypes = nil
	file_datax_proto_depIdxs = nil
}
