// Copyright 2024 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: datax.proto

package datax

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Version string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	Fields  []*DataSpec_Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
}

func (x *DataSpec) Reset() {
	*x = DataSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec) ProtoMessage() {}

func (x *DataSpec) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec.ProtoReflect.Descriptor instead.
func (*DataSpec) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{0}
}

func (x *DataSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DataSpec) GetFields() []*DataSpec_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataSpec_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// unique name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// value type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty"`
	// default value set
	DefaultValue *structpb.Value   `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty" toml:"default_value,omitempty"`
	Required     bool              `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty" toml:"required,omitempty"`
	Fields       []*DataSpec_Field `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
	// description
	Desc string `protobuf:"bytes,10,opt,name=desc,proto3" json:"desc,omitempty" toml:"desc,omitempty"`
}

func (x *DataSpec_Field) Reset() {
	*x = DataSpec_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec_Field) ProtoMessage() {}

func (x *DataSpec_Field) ProtoReflect() protoreflect.Message {
	mi := &file_datax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec_Field.ProtoReflect.Descriptor instead.
func (*DataSpec_Field) Descriptor() ([]byte, []int) {
	return file_datax_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DataSpec_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSpec_Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataSpec_Field) GetDefaultValue() *structpb.Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *DataSpec_Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DataSpec_Field) GetFields() []*DataSpec_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataSpec_Field) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_datax_proto protoreflect.FileDescriptor

var file_datax_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xcf, 0x02, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0xd8, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x3a, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x78,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x78, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datax_proto_rawDescOnce sync.Once
	file_datax_proto_rawDescData = file_datax_proto_rawDesc
)

func file_datax_proto_rawDescGZIP() []byte {
	file_datax_proto_rawDescOnce.Do(func() {
		file_datax_proto_rawDescData = protoimpl.X.CompressGZIP(file_datax_proto_rawDescData)
	})
	return file_datax_proto_rawDescData
}

var file_datax_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datax_proto_goTypes = []interface{}{
	(*DataSpec)(nil),       // 0: lynkdb.lynkx.datax.DataSpec
	(*DataSpec_Field)(nil), // 1: lynkdb.lynkx.datax.DataSpec.Field
	(*structpb.Value)(nil), // 2: google.protobuf.Value
}
var file_datax_proto_depIdxs = []int32{
	1, // 0: lynkdb.lynkx.datax.DataSpec.fields:type_name -> lynkdb.lynkx.datax.DataSpec.Field
	2, // 1: lynkdb.lynkx.datax.DataSpec.Field.default_value:type_name -> google.protobuf.Value
	1, // 2: lynkdb.lynkx.datax.DataSpec.Field.fields:type_name -> lynkdb.lynkx.datax.DataSpec.Field
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datax_proto_init() }
func file_datax_proto_init() {
	if File_datax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datax_proto_goTypes,
		DependencyIndexes: file_datax_proto_depIdxs,
		MessageInfos:      file_datax_proto_msgTypes,
	}.Build()
	File_datax_proto = out.File
	file_datax_proto_rawDesc = nil
	file_datax_proto_goTypes = nil
	file_datax_proto_depIdxs = nil
}
