// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: lynkdb/lynkapi/data.proto

package lynkapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Fields        []*SpecField      `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	PrimaryFields []string          `protobuf:"bytes,10,rep,name=primary_fields,json=primaryFields,proto3" json:"primary_fields,omitempty" toml:"primary_fields,omitempty" yaml:"primary_fields,omitempty"`
	IndexFields   []string          `protobuf:"bytes,11,rep,name=index_fields,json=indexFields,proto3" json:"index_fields,omitempty" toml:"index_fields,omitempty" yaml:"index_fields,omitempty"`
	Engine        string            `protobuf:"bytes,13,opt,name=engine,proto3" json:"engine,omitempty" toml:"engine,omitempty" yaml:"engine,omitempty"`
	Prefix        string            `protobuf:"bytes,14,opt,name=prefix,proto3" json:"prefix,omitempty" toml:"prefix,omitempty" yaml:"prefix,omitempty"`
	Options       map[string]string `protobuf:"bytes,15,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty" yaml:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DemoRows      []*TableSpec_Row  `protobuf:"bytes,16,rep,name=demo_rows,json=demoRows,proto3" json:"demo_rows,omitempty" toml:"demo_rows,omitempty" yaml:"demo_rows,omitempty"`
}

func (x *TableSpec) Reset() {
	*x = TableSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSpec) ProtoMessage() {}

func (x *TableSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSpec.ProtoReflect.Descriptor instead.
func (*TableSpec) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{0}
}

func (x *TableSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSpec) GetFields() []*SpecField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TableSpec) GetPrimaryFields() []string {
	if x != nil {
		return x.PrimaryFields
	}
	return nil
}

func (x *TableSpec) GetIndexFields() []string {
	if x != nil {
		return x.IndexFields
	}
	return nil
}

func (x *TableSpec) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TableSpec) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TableSpec) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TableSpec) GetDemoRows() []*TableSpec_Row {
	if x != nil {
		return x.DemoRows
	}
	return nil
}

type DataSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver string       `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty" toml:"driver,omitempty" yaml:"driver,omitempty" x_attrs:"name_identifier"`
	Tables []*TableSpec `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty" toml:"tables,omitempty" yaml:"tables,omitempty"`
}

func (x *DataSpec) Reset() {
	*x = DataSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec) ProtoMessage() {}

func (x *DataSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec.ProtoReflect.Descriptor instead.
func (*DataSpec) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataSpec) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DataSpec) GetTables() []*TableSpec {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DataConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" toml:"address,omitempty" yaml:"address,omitempty"`
	User      string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty" toml:"user,omitempty" yaml:"user,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" toml:"password,omitempty" yaml:"password,omitempty"`
	AccessKey string `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty" toml:"access_key,omitempty" yaml:"access_key,omitempty"`
}

func (x *DataConnect) Reset() {
	*x = DataConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConnect) ProtoMessage() {}

func (x *DataConnect) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConnect.ProtoReflect.Descriptor instead.
func (*DataConnect) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{2}
}

func (x *DataConnect) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DataConnect) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DataConnect) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DataConnect) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type DataInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string       `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name    string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Type    string       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:"table,kv"`
	Connect *DataConnect `protobuf:"bytes,8,opt,name=connect,proto3" json:"connect,omitempty" toml:"connect,omitempty" yaml:"connect,omitempty"`
	Spec    *DataSpec    `protobuf:"bytes,9,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty" yaml:"spec,omitempty"`
}

func (x *DataInstance) Reset() {
	*x = DataInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInstance) ProtoMessage() {}

func (x *DataInstance) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInstance.ProtoReflect.Descriptor instead.
func (*DataInstance) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{3}
}

func (x *DataInstance) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataInstance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataInstance) GetConnect() *DataConnect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *DataInstance) GetSpec() *DataSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DataProject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Instances []*DataInstance `protobuf:"bytes,9,rep,name=instances,proto3" json:"instances,omitempty" toml:"instances,omitempty" yaml:"instances,omitempty"`
}

func (x *DataProject) Reset() {
	*x = DataProject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProject) ProtoMessage() {}

func (x *DataProject) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProject.ProtoReflect.Descriptor instead.
func (*DataProject) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{4}
}

func (x *DataProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataProject) GetInstances() []*DataInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type DataQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string                  `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty" yaml:"instance_name,omitempty" x_attrs:"name_identifier"`
	TableName    string                  `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty" x_attrs:"name_identifier"`
	Fields       []string                `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	Filter       *DataQuery_Filter       `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
	Sort         []*DataQuery_SortFilter `protobuf:"bytes,7,rep,name=sort,proto3" json:"sort,omitempty" toml:"sort,omitempty" yaml:"sort,omitempty"`
	Offset       string                  `protobuf:"bytes,8,opt,name=offset,proto3" json:"offset,omitempty" toml:"offset,omitempty" yaml:"offset,omitempty"`
	Limit        int64                   `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty" toml:"limit,omitempty" yaml:"limit,omitempty"`
}

func (x *DataQuery) Reset() {
	*x = DataQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery) ProtoMessage() {}

func (x *DataQuery) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery.ProtoReflect.Descriptor instead.
func (*DataQuery) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{5}
}

func (x *DataQuery) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DataQuery) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataQuery) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataQuery) GetFilter() *DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DataQuery) GetSort() []*DataQuery_SortFilter {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *DataQuery) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *DataQuery) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string           `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Spec *TableSpec       `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty" yaml:"spec,omitempty"`
	Rows []*TableSpec_Row `protobuf:"bytes,9,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty" yaml:"rows,omitempty" x_attrs:"rows"`
}

func (x *DataResult) Reset() {
	*x = DataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResult) ProtoMessage() {}

func (x *DataResult) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResult.ProtoReflect.Descriptor instead.
func (*DataResult) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{6}
}

func (x *DataResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataResult) GetSpec() *TableSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DataResult) GetRows() []*TableSpec_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type DataResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Results []*DataResult `protobuf:"bytes,9,rep,name=results,proto3" json:"results,omitempty" toml:"results,omitempty" yaml:"results,omitempty"`
}

func (x *DataResults) Reset() {
	*x = DataResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResults) ProtoMessage() {}

func (x *DataResults) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResults.ProtoReflect.Descriptor instead.
func (*DataResults) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{7}
}

func (x *DataResults) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataResults) GetResults() []*DataResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TableSpec_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" yaml:"id,omitempty"`
	Values []*structpb.Value          `protobuf:"bytes,9,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty" yaml:"values,omitempty"`
	Fields map[string]*structpb.Value `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TableSpec_Row) Reset() {
	*x = TableSpec_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSpec_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSpec_Row) ProtoMessage() {}

func (x *TableSpec_Row) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSpec_Row.ProtoReflect.Descriptor instead.
func (*TableSpec_Row) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TableSpec_Row) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TableSpec_Row) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *TableSpec_Row) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataQuery_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:",and,or"`
	Name  string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Value string              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty" yaml:"value,omitempty"`
	Inner []*DataQuery_Filter `protobuf:"bytes,4,rep,name=inner,proto3" json:"inner,omitempty" toml:"inner,omitempty" yaml:"inner,omitempty"`
}

func (x *DataQuery_Filter) Reset() {
	*x = DataQuery_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery_Filter) ProtoMessage() {}

func (x *DataQuery_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery_Filter.ProtoReflect.Descriptor instead.
func (*DataQuery_Filter) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DataQuery_Filter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataQuery_Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataQuery_Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DataQuery_Filter) GetInner() []*DataQuery_Filter {
	if x != nil {
		return x.Inner
	}
	return nil
}

type DataQuery_SortFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:",asc,desc"`
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty" toml:"field,omitempty" yaml:"field,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty" yaml:"value,omitempty"`
}

func (x *DataQuery_SortFilter) Reset() {
	*x = DataQuery_SortFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery_SortFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery_SortFilter) ProtoMessage() {}

func (x *DataQuery_SortFilter) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery_SortFilter.ProtoReflect.Descriptor instead.
func (*DataQuery_SortFilter) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_data_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DataQuery_SortFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataQuery_SortFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DataQuery_SortFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_lynkdb_lynkapi_data_proto protoreflect.FileDescriptor

var file_lynkdb_lynkapi_data_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6c, 0x79, 0x6e,
	0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x04, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x12, 0x40, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79,
	0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x64, 0x65, 0x6d, 0x6f, 0x5f, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x08, 0x64, 0x65, 0x6d, 0x6f, 0x52, 0x6f, 0x77,
	0x73, 0x1a, 0xdb, 0x01, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x51, 0x0a, 0x0b,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x55, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12,
	0x31, 0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x06, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x22, 0x76, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x2c,
	0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x5d, 0x0a, 0x0b,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x3a, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xd7, 0x03, 0x0a, 0x09,
	0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x38, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x38, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x7e, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x36, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x4c, 0x0a, 0x0a, 0x53, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x31, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x57,
	0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x0d, 0x48, 0x03, 0x5a, 0x09, 0x2e, 0x3b, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lynkdb_lynkapi_data_proto_rawDescOnce sync.Once
	file_lynkdb_lynkapi_data_proto_rawDescData = file_lynkdb_lynkapi_data_proto_rawDesc
)

func file_lynkdb_lynkapi_data_proto_rawDescGZIP() []byte {
	file_lynkdb_lynkapi_data_proto_rawDescOnce.Do(func() {
		file_lynkdb_lynkapi_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_lynkdb_lynkapi_data_proto_rawDescData)
	})
	return file_lynkdb_lynkapi_data_proto_rawDescData
}

var file_lynkdb_lynkapi_data_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lynkdb_lynkapi_data_proto_goTypes = []interface{}{
	(*TableSpec)(nil),            // 0: lynkdb.lynkapi.TableSpec
	(*DataSpec)(nil),             // 1: lynkdb.lynkapi.DataSpec
	(*DataConnect)(nil),          // 2: lynkdb.lynkapi.DataConnect
	(*DataInstance)(nil),         // 3: lynkdb.lynkapi.DataInstance
	(*DataProject)(nil),          // 4: lynkdb.lynkapi.DataProject
	(*DataQuery)(nil),            // 5: lynkdb.lynkapi.DataQuery
	(*DataResult)(nil),           // 6: lynkdb.lynkapi.DataResult
	(*DataResults)(nil),          // 7: lynkdb.lynkapi.DataResults
	(*TableSpec_Row)(nil),        // 8: lynkdb.lynkapi.TableSpec.Row
	nil,                          // 9: lynkdb.lynkapi.TableSpec.OptionsEntry
	nil,                          // 10: lynkdb.lynkapi.TableSpec.Row.FieldsEntry
	(*DataQuery_Filter)(nil),     // 11: lynkdb.lynkapi.DataQuery.Filter
	(*DataQuery_SortFilter)(nil), // 12: lynkdb.lynkapi.DataQuery.SortFilter
	(*SpecField)(nil),            // 13: lynkdb.lynkapi.SpecField
	(*structpb.Value)(nil),       // 14: google.protobuf.Value
}
var file_lynkdb_lynkapi_data_proto_depIdxs = []int32{
	13, // 0: lynkdb.lynkapi.TableSpec.fields:type_name -> lynkdb.lynkapi.SpecField
	9,  // 1: lynkdb.lynkapi.TableSpec.options:type_name -> lynkdb.lynkapi.TableSpec.OptionsEntry
	8,  // 2: lynkdb.lynkapi.TableSpec.demo_rows:type_name -> lynkdb.lynkapi.TableSpec.Row
	0,  // 3: lynkdb.lynkapi.DataSpec.tables:type_name -> lynkdb.lynkapi.TableSpec
	2,  // 4: lynkdb.lynkapi.DataInstance.connect:type_name -> lynkdb.lynkapi.DataConnect
	1,  // 5: lynkdb.lynkapi.DataInstance.spec:type_name -> lynkdb.lynkapi.DataSpec
	3,  // 6: lynkdb.lynkapi.DataProject.instances:type_name -> lynkdb.lynkapi.DataInstance
	11, // 7: lynkdb.lynkapi.DataQuery.filter:type_name -> lynkdb.lynkapi.DataQuery.Filter
	12, // 8: lynkdb.lynkapi.DataQuery.sort:type_name -> lynkdb.lynkapi.DataQuery.SortFilter
	0,  // 9: lynkdb.lynkapi.DataResult.spec:type_name -> lynkdb.lynkapi.TableSpec
	8,  // 10: lynkdb.lynkapi.DataResult.rows:type_name -> lynkdb.lynkapi.TableSpec.Row
	6,  // 11: lynkdb.lynkapi.DataResults.results:type_name -> lynkdb.lynkapi.DataResult
	14, // 12: lynkdb.lynkapi.TableSpec.Row.values:type_name -> google.protobuf.Value
	10, // 13: lynkdb.lynkapi.TableSpec.Row.fields:type_name -> lynkdb.lynkapi.TableSpec.Row.FieldsEntry
	14, // 14: lynkdb.lynkapi.TableSpec.Row.FieldsEntry.value:type_name -> google.protobuf.Value
	11, // 15: lynkdb.lynkapi.DataQuery.Filter.inner:type_name -> lynkdb.lynkapi.DataQuery.Filter
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_lynkdb_lynkapi_data_proto_init() }
func file_lynkdb_lynkapi_data_proto_init() {
	if File_lynkdb_lynkapi_data_proto != nil {
		return
	}
	file_lynkdb_lynkapi_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lynkdb_lynkapi_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataProject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSpec_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery_SortFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lynkdb_lynkapi_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lynkdb_lynkapi_data_proto_goTypes,
		DependencyIndexes: file_lynkdb_lynkapi_data_proto_depIdxs,
		MessageInfos:      file_lynkdb_lynkapi_data_proto_msgTypes,
	}.Build()
	File_lynkdb_lynkapi_data_proto = out.File
	file_lynkdb_lynkapi_data_proto_rawDesc = nil
	file_lynkdb_lynkapi_data_proto_goTypes = nil
	file_lynkdb_lynkapi_data_proto_depIdxs = nil
}
