// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: lynkapi/data.proto

package lynkapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataDict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id  string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" yaml:"id,omitempty" x_attrs:"primary_key,rand_hex(8)"`
	Pid string `protobuf:"bytes,4,opt,name=pid,proto3" json:"pid,omitempty" toml:"pid,omitempty" yaml:"pid,omitempty"` // parent-id
	// metadata
	Ns       string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty" toml:"ns,omitempty" yaml:"ns,omitempty" x_attrs:"namespace_identifier"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"unique_key"`
	RefTable string `protobuf:"bytes,8,opt,name=ref_table,json=refTable,proto3" json:"ref_table,omitempty" toml:"ref_table,omitempty" yaml:"ref_table,omitempty" x_attrs:""`
	// information
	DisplayName string `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" toml:"display_name,omitempty" yaml:"display_name,omitempty"`
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty" yaml:"description,omitempty"`
	Attrs     []string                   `protobuf:"bytes,13,rep,name=attrs,proto3" json:"attrs,omitempty" toml:"attrs,omitempty" yaml:"attrs,omitempty"`
	ExtFields map[string]*structpb.Value `protobuf:"bytes,17,rep,name=ext_fields,json=extFields,proto3" json:"ext_fields,omitempty" toml:"ext_fields,omitempty" yaml:"ext_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// style
	Order   int32  `protobuf:"varint,32,opt,name=order,proto3" json:"order,omitempty" toml:"order,omitempty" yaml:"order,omitempty" x_range:"0,4,9"`
	Version uint64 `protobuf:"varint,33,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty" yaml:"version,omitempty"`
}

func (x *DataDict) Reset() {
	*x = DataDict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDict) ProtoMessage() {}

func (x *DataDict) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDict.ProtoReflect.Descriptor instead.
func (*DataDict) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{0}
}

func (x *DataDict) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataDict) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *DataDict) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *DataDict) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataDict) GetRefTable() string {
	if x != nil {
		return x.RefTable
	}
	return ""
}

func (x *DataDict) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DataDict) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataDict) GetAttrs() []string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *DataDict) GetExtFields() map[string]*structpb.Value {
	if x != nil {
		return x.ExtFields
	}
	return nil
}

func (x *DataDict) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *DataDict) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DataRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty" yaml:"id,omitempty"`
	Values []*structpb.Value `protobuf:"bytes,9,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty" yaml:"values,omitempty"`
	// field.tag_name = any-value
	Fields map[string]*structpb.Value `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// ex ...
	InterOrder int64 `protobuf:"varint,32,opt,name=inter_order,json=interOrder,proto3" json:"inter_order,omitempty" toml:"inter_order,omitempty" yaml:"inter_order,omitempty"`
}

func (x *DataRow) Reset() {
	*x = DataRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRow) ProtoMessage() {}

func (x *DataRow) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRow.ProtoReflect.Descriptor instead.
func (*DataRow) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataRow) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DataRow) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataRow) GetInterOrder() int64 {
	if x != nil {
		return x.InterOrder
	}
	return 0
}

type DataCol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseIntValue int64     `protobuf:"varint,6,opt,name=base_int_value,json=baseIntValue,proto3" json:"base_int_value,omitempty" toml:"base_int_value,omitempty" yaml:"base_int_value,omitempty"`
	IntValues    []int64   `protobuf:"varint,7,rep,packed,name=int_values,json=intValues,proto3" json:"int_values,omitempty" toml:"int_values,omitempty" yaml:"int_values,omitempty"`
	StringValues []string  `protobuf:"bytes,9,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty" toml:"string_values,omitempty" yaml:"string_values,omitempty"`
	BytesValues  [][]byte  `protobuf:"bytes,11,rep,name=bytes_values,json=bytesValues,proto3" json:"bytes_values,omitempty" toml:"bytes_values,omitempty" yaml:"bytes_values,omitempty"`
	FloatValues  []float32 `protobuf:"fixed32,13,rep,packed,name=float_values,json=floatValues,proto3" json:"float_values,omitempty" toml:"float_values,omitempty" yaml:"float_values,omitempty"`
}

func (x *DataCol) Reset() {
	*x = DataCol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCol) ProtoMessage() {}

func (x *DataCol) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCol.ProtoReflect.Descriptor instead.
func (*DataCol) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{2}
}

func (x *DataCol) GetBaseIntValue() int64 {
	if x != nil {
		return x.BaseIntValue
	}
	return 0
}

func (x *DataCol) GetIntValues() []int64 {
	if x != nil {
		return x.IntValues
	}
	return nil
}

func (x *DataCol) GetStringValues() []string {
	if x != nil {
		return x.StringValues
	}
	return nil
}

func (x *DataCol) GetBytesValues() [][]byte {
	if x != nil {
		return x.BytesValues
	}
	return nil
}

func (x *DataCol) GetFloatValues() []float32 {
	if x != nil {
		return x.FloatValues
	}
	return nil
}

type TableSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Kind          string            `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Fields        []*FieldSpec      `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	PrimaryFields []string          `protobuf:"bytes,10,rep,name=primary_fields,json=primaryFields,proto3" json:"primary_fields,omitempty" toml:"primary_fields,omitempty" yaml:"primary_fields,omitempty"`
	IndexFields   []string          `protobuf:"bytes,11,rep,name=index_fields,json=indexFields,proto3" json:"index_fields,omitempty" toml:"index_fields,omitempty" yaml:"index_fields,omitempty"`
	Engine        string            `protobuf:"bytes,13,opt,name=engine,proto3" json:"engine,omitempty" toml:"engine,omitempty" yaml:"engine,omitempty"`
	Prefix        string            `protobuf:"bytes,14,opt,name=prefix,proto3" json:"prefix,omitempty" toml:"prefix,omitempty" yaml:"prefix,omitempty"`
	Options       map[string]string `protobuf:"bytes,15,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty" yaml:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DemoRows      []*DataRow        `protobuf:"bytes,16,rep,name=demo_rows,json=demoRows,proto3" json:"demo_rows,omitempty" toml:"demo_rows,omitempty" yaml:"demo_rows,omitempty"`
}

func (x *TableSpec) Reset() {
	*x = TableSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSpec) ProtoMessage() {}

func (x *TableSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSpec.ProtoReflect.Descriptor instead.
func (*TableSpec) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{3}
}

func (x *TableSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TableSpec) GetFields() []*FieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TableSpec) GetPrimaryFields() []string {
	if x != nil {
		return x.PrimaryFields
	}
	return nil
}

func (x *TableSpec) GetIndexFields() []string {
	if x != nil {
		return x.IndexFields
	}
	return nil
}

func (x *TableSpec) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TableSpec) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TableSpec) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TableSpec) GetDemoRows() []*DataRow {
	if x != nil {
		return x.DemoRows
	}
	return nil
}

type DataSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver string       `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty" toml:"driver,omitempty" yaml:"driver,omitempty" x_attrs:"name_identifier"`
	Type   string       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:"table,kv,oneobject"`
	Tables []*TableSpec `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty" toml:"tables,omitempty" yaml:"tables,omitempty"`
}

func (x *DataSpec) Reset() {
	*x = DataSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec) ProtoMessage() {}

func (x *DataSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec.ProtoReflect.Descriptor instead.
func (*DataSpec) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{4}
}

func (x *DataSpec) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DataSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataSpec) GetTables() []*TableSpec {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DataConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" toml:"address,omitempty" yaml:"address,omitempty"`
	User      string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty" toml:"user,omitempty" yaml:"user,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" toml:"password,omitempty" yaml:"password,omitempty"`
	AccessKey string `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty" toml:"access_key,omitempty" yaml:"access_key,omitempty"`
}

func (x *DataConnect) Reset() {
	*x = DataConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConnect) ProtoMessage() {}

func (x *DataConnect) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConnect.ProtoReflect.Descriptor instead.
func (*DataConnect) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{5}
}

func (x *DataConnect) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DataConnect) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DataConnect) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DataConnect) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type DataInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string       `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name    string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Type    string       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:"table,kv,oneobject"`
	Connect *DataConnect `protobuf:"bytes,8,opt,name=connect,proto3" json:"connect,omitempty" toml:"connect,omitempty" yaml:"connect,omitempty"`
	Spec    *DataSpec    `protobuf:"bytes,9,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty" yaml:"spec,omitempty"`
}

func (x *DataInstance) Reset() {
	*x = DataInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInstance) ProtoMessage() {}

func (x *DataInstance) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInstance.ProtoReflect.Descriptor instead.
func (*DataInstance) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{6}
}

func (x *DataInstance) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataInstance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataInstance) GetConnect() *DataConnect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *DataInstance) GetSpec() *DataSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DataProject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty" x_attrs:"name_identifier"`
	Instances []*DataInstance `protobuf:"bytes,9,rep,name=instances,proto3" json:"instances,omitempty" toml:"instances,omitempty" yaml:"instances,omitempty"`
}

func (x *DataProject) Reset() {
	*x = DataProject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProject) ProtoMessage() {}

func (x *DataProject) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProject.ProtoReflect.Descriptor instead.
func (*DataProject) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{7}
}

func (x *DataProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataProject) GetInstances() []*DataInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type DataQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string                `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty" yaml:"instance_name,omitempty" x_attrs:"name_identifier"`
	TableName    string                `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty" x_attrs:"name_identifier"`
	Fields       []string              `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	Filter       *DataQuery_Filter     `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
	Sort         *DataQuery_SortFilter `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty" toml:"sort,omitempty" yaml:"sort,omitempty"`
	Offset       string                `protobuf:"bytes,8,opt,name=offset,proto3" json:"offset,omitempty" toml:"offset,omitempty" yaml:"offset,omitempty"`
	Limit        int64                 `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty" toml:"limit,omitempty" yaml:"limit,omitempty"`
}

func (x *DataQuery) Reset() {
	*x = DataQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery) ProtoMessage() {}

func (x *DataQuery) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery.ProtoReflect.Descriptor instead.
func (*DataQuery) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{8}
}

func (x *DataQuery) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DataQuery) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataQuery) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataQuery) GetFilter() *DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DataQuery) GetSort() *DataQuery_SortFilter {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *DataQuery) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *DataQuery) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DataInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string            `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty" yaml:"instance_name,omitempty" x_attrs:"name_identifier"`
	TableName    string            `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty" x_attrs:"name_identifier"`
	Fields       []string          `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	Values       []*structpb.Value `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty" yaml:"values,omitempty"`
}

func (x *DataInsert) Reset() {
	*x = DataInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInsert) ProtoMessage() {}

func (x *DataInsert) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInsert.ProtoReflect.Descriptor instead.
func (*DataInsert) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{9}
}

func (x *DataInsert) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DataInsert) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataInsert) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataInsert) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type DataUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string            `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty" yaml:"instance_name,omitempty" x_attrs:"name_identifier"`
	TableName    string            `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty" x_attrs:"name_identifier"`
	Fields       []string          `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" yaml:"fields,omitempty"`
	Values       []*structpb.Value `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty" yaml:"values,omitempty"`
	Filter       *DataQuery_Filter `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
}

func (x *DataUpdate) Reset() {
	*x = DataUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUpdate) ProtoMessage() {}

func (x *DataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUpdate.ProtoReflect.Descriptor instead.
func (*DataUpdate) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{10}
}

func (x *DataUpdate) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DataUpdate) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataUpdate) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataUpdate) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DataUpdate) GetFilter() *DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DataDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string            `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty" yaml:"instance_name,omitempty" x_attrs:"name_identifier"`
	TableName    string            `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty" x_attrs:"name_identifier"`
	Filter       *DataQuery_Filter `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
}

func (x *DataDelete) Reset() {
	*x = DataDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDelete) ProtoMessage() {}

func (x *DataDelete) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDelete.ProtoReflect.Descriptor instead.
func (*DataDelete) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{11}
}

func (x *DataDelete) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DataDelete) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataDelete) GetFilter() *DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind       string            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status     *ServiceStatus    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Name       string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Spec       *TableSpec        `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty" yaml:"spec,omitempty"`
	Rows       []*DataRow        `protobuf:"bytes,9,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty" yaml:"rows,omitempty" x_attrs:"rows"`
	Cols       []*DataCol        `protobuf:"bytes,19,rep,name=cols,proto3" json:"cols,omitempty" toml:"cols,omitempty" yaml:"cols,omitempty" x_attrs:"cols"`
	Objs       []*structpb.Value `protobuf:"bytes,20,rep,name=objs,proto3" json:"objs,omitempty" toml:"objs,omitempty" yaml:"objs,omitempty"`
	NextOffset string            `protobuf:"bytes,10,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty" toml:"next_offset,omitempty" yaml:"next_offset,omitempty"`
}

func (x *DataResult) Reset() {
	*x = DataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResult) ProtoMessage() {}

func (x *DataResult) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResult.ProtoReflect.Descriptor instead.
func (*DataResult) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{12}
}

func (x *DataResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataResult) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DataResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataResult) GetSpec() *TableSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DataResult) GetRows() []*DataRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DataResult) GetCols() []*DataCol {
	if x != nil {
		return x.Cols
	}
	return nil
}

func (x *DataResult) GetObjs() []*structpb.Value {
	if x != nil {
		return x.Objs
	}
	return nil
}

func (x *DataResult) GetNextOffset() string {
	if x != nil {
		return x.NextOffset
	}
	return ""
}

type DataResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string         `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status  *ServiceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Results []*DataResult  `protobuf:"bytes,9,rep,name=results,proto3" json:"results,omitempty" toml:"results,omitempty" yaml:"results,omitempty"`
}

func (x *DataResults) Reset() {
	*x = DataResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResults) ProtoMessage() {}

func (x *DataResults) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResults.ProtoReflect.Descriptor instead.
func (*DataResults) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{13}
}

func (x *DataResults) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataResults) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DataResults) GetResults() []*DataResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DataQuery_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:",and,or"`
	Field string              `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty" toml:"field,omitempty" yaml:"field,omitempty"`
	Value *structpb.Value     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty" yaml:"value,omitempty"`
	Inner []*DataQuery_Filter `protobuf:"bytes,4,rep,name=inner,proto3" json:"inner,omitempty" toml:"inner,omitempty" yaml:"inner,omitempty"`
}

func (x *DataQuery_Filter) Reset() {
	*x = DataQuery_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery_Filter) ProtoMessage() {}

func (x *DataQuery_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery_Filter.ProtoReflect.Descriptor instead.
func (*DataQuery_Filter) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DataQuery_Filter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataQuery_Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DataQuery_Filter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataQuery_Filter) GetInner() []*DataQuery_Filter {
	if x != nil {
		return x.Inner
	}
	return nil
}

type DataQuery_SortFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty" yaml:"type,omitempty" x_enums:",asc,desc"`
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty" toml:"field,omitempty" yaml:"field,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty" yaml:"value,omitempty"` // TODO repeated SortFilter inner = 4;
}

func (x *DataQuery_SortFilter) Reset() {
	*x = DataQuery_SortFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_data_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery_SortFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery_SortFilter) ProtoMessage() {}

func (x *DataQuery_SortFilter) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_data_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery_SortFilter.ProtoReflect.Descriptor instead.
func (*DataQuery_SortFilter) Descriptor() ([]byte, []int) {
	return file_lynkapi_data_proto_rawDescGZIP(), []int{8, 1}
}

func (x *DataQuery_SortFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataQuery_SortFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DataQuery_SortFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_lynkapi_data_proto protoreflect.FileDescriptor

var file_lynkapi_data_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6c, 0x79, 0x6e,
	0x6b, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8f, 0x03, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x66, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x0d, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x65, 0x78,
	0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x63,
	0x74, 0x2e, 0x45, 0x78, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x09, 0x65, 0x78, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x20, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x21, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x54, 0x0a, 0x0e, 0x45,
	0x78, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0xf3, 0x01, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x77, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x34, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x77, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x20, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x1a, 0x51, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb9, 0x01, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x0d, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0xff, 0x02, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x39, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x65,
	0x6d, 0x6f, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x77, 0x52,
	0x08, 0x64, 0x65, 0x6d, 0x6f, 0x52, 0x6f, 0x77, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x62, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x0b, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65,
	0x79, 0x22, 0xa1, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x56, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x79,
	0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xdd, 0x03,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x91, 0x01, 0x0a, 0x06,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f,
	0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a,
	0x4c, 0x0a, 0x0a, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x98, 0x01,
	0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74,
	0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa5, 0x02, 0x0a,
	0x0a, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x24, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x13, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f,
	0x6c, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x6f, 0x62, 0x6a, 0x73, 0x18,
	0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6f,
	0x62, 0x6a, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x30, 0x48, 0x03, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2f, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70,
	0x69, 0x3b, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lynkapi_data_proto_rawDescOnce sync.Once
	file_lynkapi_data_proto_rawDescData = file_lynkapi_data_proto_rawDesc
)

func file_lynkapi_data_proto_rawDescGZIP() []byte {
	file_lynkapi_data_proto_rawDescOnce.Do(func() {
		file_lynkapi_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_lynkapi_data_proto_rawDescData)
	})
	return file_lynkapi_data_proto_rawDescData
}

var file_lynkapi_data_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lynkapi_data_proto_goTypes = []interface{}{
	(*DataDict)(nil),             // 0: lynkapi.DataDict
	(*DataRow)(nil),              // 1: lynkapi.DataRow
	(*DataCol)(nil),              // 2: lynkapi.DataCol
	(*TableSpec)(nil),            // 3: lynkapi.TableSpec
	(*DataSpec)(nil),             // 4: lynkapi.DataSpec
	(*DataConnect)(nil),          // 5: lynkapi.DataConnect
	(*DataInstance)(nil),         // 6: lynkapi.DataInstance
	(*DataProject)(nil),          // 7: lynkapi.DataProject
	(*DataQuery)(nil),            // 8: lynkapi.DataQuery
	(*DataInsert)(nil),           // 9: lynkapi.DataInsert
	(*DataUpdate)(nil),           // 10: lynkapi.DataUpdate
	(*DataDelete)(nil),           // 11: lynkapi.DataDelete
	(*DataResult)(nil),           // 12: lynkapi.DataResult
	(*DataResults)(nil),          // 13: lynkapi.DataResults
	nil,                          // 14: lynkapi.DataDict.ExtFieldsEntry
	nil,                          // 15: lynkapi.DataRow.FieldsEntry
	nil,                          // 16: lynkapi.TableSpec.OptionsEntry
	(*DataQuery_Filter)(nil),     // 17: lynkapi.DataQuery.Filter
	(*DataQuery_SortFilter)(nil), // 18: lynkapi.DataQuery.SortFilter
	(*structpb.Value)(nil),       // 19: google.protobuf.Value
	(*FieldSpec)(nil),            // 20: lynkapi.FieldSpec
	(*ServiceStatus)(nil),        // 21: lynkapi.ServiceStatus
}
var file_lynkapi_data_proto_depIdxs = []int32{
	14, // 0: lynkapi.DataDict.ext_fields:type_name -> lynkapi.DataDict.ExtFieldsEntry
	19, // 1: lynkapi.DataRow.values:type_name -> google.protobuf.Value
	15, // 2: lynkapi.DataRow.fields:type_name -> lynkapi.DataRow.FieldsEntry
	20, // 3: lynkapi.TableSpec.fields:type_name -> lynkapi.FieldSpec
	16, // 4: lynkapi.TableSpec.options:type_name -> lynkapi.TableSpec.OptionsEntry
	1,  // 5: lynkapi.TableSpec.demo_rows:type_name -> lynkapi.DataRow
	3,  // 6: lynkapi.DataSpec.tables:type_name -> lynkapi.TableSpec
	5,  // 7: lynkapi.DataInstance.connect:type_name -> lynkapi.DataConnect
	4,  // 8: lynkapi.DataInstance.spec:type_name -> lynkapi.DataSpec
	6,  // 9: lynkapi.DataProject.instances:type_name -> lynkapi.DataInstance
	17, // 10: lynkapi.DataQuery.filter:type_name -> lynkapi.DataQuery.Filter
	18, // 11: lynkapi.DataQuery.sort:type_name -> lynkapi.DataQuery.SortFilter
	19, // 12: lynkapi.DataInsert.values:type_name -> google.protobuf.Value
	19, // 13: lynkapi.DataUpdate.values:type_name -> google.protobuf.Value
	17, // 14: lynkapi.DataUpdate.filter:type_name -> lynkapi.DataQuery.Filter
	17, // 15: lynkapi.DataDelete.filter:type_name -> lynkapi.DataQuery.Filter
	21, // 16: lynkapi.DataResult.status:type_name -> lynkapi.ServiceStatus
	3,  // 17: lynkapi.DataResult.spec:type_name -> lynkapi.TableSpec
	1,  // 18: lynkapi.DataResult.rows:type_name -> lynkapi.DataRow
	2,  // 19: lynkapi.DataResult.cols:type_name -> lynkapi.DataCol
	19, // 20: lynkapi.DataResult.objs:type_name -> google.protobuf.Value
	21, // 21: lynkapi.DataResults.status:type_name -> lynkapi.ServiceStatus
	12, // 22: lynkapi.DataResults.results:type_name -> lynkapi.DataResult
	19, // 23: lynkapi.DataDict.ExtFieldsEntry.value:type_name -> google.protobuf.Value
	19, // 24: lynkapi.DataRow.FieldsEntry.value:type_name -> google.protobuf.Value
	19, // 25: lynkapi.DataQuery.Filter.value:type_name -> google.protobuf.Value
	17, // 26: lynkapi.DataQuery.Filter.inner:type_name -> lynkapi.DataQuery.Filter
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_lynkapi_data_proto_init() }
func file_lynkapi_data_proto_init() {
	if File_lynkapi_data_proto != nil {
		return
	}
	file_lynkapi_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lynkapi_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataProject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_data_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery_SortFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lynkapi_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lynkapi_data_proto_goTypes,
		DependencyIndexes: file_lynkapi_data_proto_depIdxs,
		MessageInfos:      file_lynkapi_data_proto_msgTypes,
	}.Build()
	File_lynkapi_data_proto = out.File
	file_lynkapi_data_proto_rawDesc = nil
	file_lynkapi_data_proto_goTypes = nil
	file_lynkapi_data_proto_depIdxs = nil
}
