// Copyright 2024 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: lynkdb/lynkapi/service.proto

package lynkapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty" toml:"code,omitempty" yaml:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" toml:"message,omitempty" yaml:"message,omitempty"`
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServiceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	RequestSpec  *Spec  `protobuf:"bytes,4,opt,name=request_spec,json=requestSpec,proto3" json:"request_spec,omitempty" toml:"request_spec,omitempty" yaml:"request_spec,omitempty"`
	ResponseSpec *Spec  `protobuf:"bytes,6,opt,name=response_spec,json=responseSpec,proto3" json:"response_spec,omitempty" toml:"response_spec,omitempty" yaml:"response_spec,omitempty"`
}

func (x *ServiceMethod) Reset() {
	*x = ServiceMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMethod) ProtoMessage() {}

func (x *ServiceMethod) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMethod.ProtoReflect.Descriptor instead.
func (*ServiceMethod) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMethod) GetRequestSpec() *Spec {
	if x != nil {
		return x.RequestSpec
	}
	return nil
}

func (x *ServiceMethod) GetResponseSpec() *Spec {
	if x != nil {
		return x.ResponseSpec
	}
	return nil
}

type ServiceInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Methods []*ServiceMethod `protobuf:"bytes,9,rep,name=methods,proto3" json:"methods,omitempty" toml:"methods,omitempty" yaml:"methods,omitempty"`
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInstance) GetMethods() []*ServiceMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ApiListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiListRequest) Reset() {
	*x = ApiListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListRequest) ProtoMessage() {}

func (x *ApiListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListRequest.ProtoReflect.Descriptor instead.
func (*ApiListRequest) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{3}
}

type ApiListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string             `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status   *ServiceStatus     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Services []*ServiceInstance `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" toml:"services,omitempty" yaml:"services,omitempty"`
}

func (x *ApiListResponse) Reset() {
	*x = ApiListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListResponse) ProtoMessage() {}

func (x *ApiListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListResponse.ProtoReflect.Descriptor instead.
func (*ApiListResponse) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApiListResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiListResponse) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ApiListResponse) GetServices() []*ServiceInstance {
	if x != nil {
		return x.Services
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string           `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" toml:"service_name,omitempty" yaml:"service_name,omitempty"`
	MethodName  string           `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty" toml:"method_name,omitempty" yaml:"method_name,omitempty"`
	Data        *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Request) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *Request) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string           `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status *ServiceStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Data   *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkdb_lynkapi_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_lynkdb_lynkapi_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_lynkdb_lynkapi_service_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Response) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_lynkdb_lynkapi_service_proto protoreflect.FileDescriptor

var file_lynkdb_lynkapi_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6c, 0x79,
	0x6e, 0x6b, 0x64, 0x62, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2f,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x39, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x65, 0x63, 0x22, 0x5e, 0x0a, 0x0f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41,
	0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x99, 0x01,
	0x0a, 0x0f, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xdf, 0x01, 0x0a, 0x0c, 0x44,
	0x61, 0x74, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x07, 0x41,
	0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x45, 0x78, 0x65,
	0x63, 0x12, 0x17, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x1a,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0d, 0x48, 0x03,
	0x5a, 0x09, 0x2e, 0x3b, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_lynkdb_lynkapi_service_proto_rawDescOnce sync.Once
	file_lynkdb_lynkapi_service_proto_rawDescData = file_lynkdb_lynkapi_service_proto_rawDesc
)

func file_lynkdb_lynkapi_service_proto_rawDescGZIP() []byte {
	file_lynkdb_lynkapi_service_proto_rawDescOnce.Do(func() {
		file_lynkdb_lynkapi_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_lynkdb_lynkapi_service_proto_rawDescData)
	})
	return file_lynkdb_lynkapi_service_proto_rawDescData
}

var file_lynkdb_lynkapi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lynkdb_lynkapi_service_proto_goTypes = []interface{}{
	(*ServiceStatus)(nil),   // 0: lynkdb.lynkapi.ServiceStatus
	(*ServiceMethod)(nil),   // 1: lynkdb.lynkapi.ServiceMethod
	(*ServiceInstance)(nil), // 2: lynkdb.lynkapi.ServiceInstance
	(*ApiListRequest)(nil),  // 3: lynkdb.lynkapi.ApiListRequest
	(*ApiListResponse)(nil), // 4: lynkdb.lynkapi.ApiListResponse
	(*Request)(nil),         // 5: lynkdb.lynkapi.Request
	(*Response)(nil),        // 6: lynkdb.lynkapi.Response
	(*Spec)(nil),            // 7: lynkdb.lynkapi.Spec
	(*structpb.Struct)(nil), // 8: google.protobuf.Struct
	(*DataQuery)(nil),       // 9: lynkdb.lynkapi.DataQuery
	(*DataResult)(nil),      // 10: lynkdb.lynkapi.DataResult
}
var file_lynkdb_lynkapi_service_proto_depIdxs = []int32{
	7,  // 0: lynkdb.lynkapi.ServiceMethod.request_spec:type_name -> lynkdb.lynkapi.Spec
	7,  // 1: lynkdb.lynkapi.ServiceMethod.response_spec:type_name -> lynkdb.lynkapi.Spec
	1,  // 2: lynkdb.lynkapi.ServiceInstance.methods:type_name -> lynkdb.lynkapi.ServiceMethod
	0,  // 3: lynkdb.lynkapi.ApiListResponse.status:type_name -> lynkdb.lynkapi.ServiceStatus
	2,  // 4: lynkdb.lynkapi.ApiListResponse.services:type_name -> lynkdb.lynkapi.ServiceInstance
	8,  // 5: lynkdb.lynkapi.Request.data:type_name -> google.protobuf.Struct
	0,  // 6: lynkdb.lynkapi.Response.status:type_name -> lynkdb.lynkapi.ServiceStatus
	8,  // 7: lynkdb.lynkapi.Response.data:type_name -> google.protobuf.Struct
	3,  // 8: lynkdb.lynkapi.DataxService.ApiList:input_type -> lynkdb.lynkapi.ApiListRequest
	5,  // 9: lynkdb.lynkapi.DataxService.Exec:input_type -> lynkdb.lynkapi.Request
	9,  // 10: lynkdb.lynkapi.DataxService.DataQuery:input_type -> lynkdb.lynkapi.DataQuery
	4,  // 11: lynkdb.lynkapi.DataxService.ApiList:output_type -> lynkdb.lynkapi.ApiListResponse
	6,  // 12: lynkdb.lynkapi.DataxService.Exec:output_type -> lynkdb.lynkapi.Response
	10, // 13: lynkdb.lynkapi.DataxService.DataQuery:output_type -> lynkdb.lynkapi.DataResult
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_lynkdb_lynkapi_service_proto_init() }
func file_lynkdb_lynkapi_service_proto_init() {
	if File_lynkdb_lynkapi_service_proto != nil {
		return
	}
	file_lynkdb_lynkapi_type_proto_init()
	file_lynkdb_lynkapi_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lynkdb_lynkapi_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkdb_lynkapi_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lynkdb_lynkapi_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lynkdb_lynkapi_service_proto_goTypes,
		DependencyIndexes: file_lynkdb_lynkapi_service_proto_depIdxs,
		MessageInfos:      file_lynkdb_lynkapi_service_proto_msgTypes,
	}.Build()
	File_lynkdb_lynkapi_service_proto = out.File
	file_lynkdb_lynkapi_service_proto_rawDesc = nil
	file_lynkdb_lynkapi_service_proto_goTypes = nil
	file_lynkdb_lynkapi_service_proto_depIdxs = nil
}
