// Copyright 2024 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: lynkapi/service.proto

package lynkapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	RequestSpec  *TypeSpec `protobuf:"bytes,4,opt,name=request_spec,json=requestSpec,proto3" json:"request_spec,omitempty" toml:"request_spec,omitempty" yaml:"request_spec,omitempty"`
	ResponseSpec *TypeSpec `protobuf:"bytes,6,opt,name=response_spec,json=responseSpec,proto3" json:"response_spec,omitempty" toml:"response_spec,omitempty" yaml:"response_spec,omitempty"`
}

func (x *ServiceMethod) Reset() {
	*x = ServiceMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMethod) ProtoMessage() {}

func (x *ServiceMethod) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMethod.ProtoReflect.Descriptor instead.
func (*ServiceMethod) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMethod) GetRequestSpec() *TypeSpec {
	if x != nil {
		return x.RequestSpec
	}
	return nil
}

func (x *ServiceMethod) GetResponseSpec() *TypeSpec {
	if x != nil {
		return x.ResponseSpec
	}
	return nil
}

type ServiceInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Methods []*ServiceMethod `protobuf:"bytes,9,rep,name=methods,proto3" json:"methods,omitempty" toml:"methods,omitempty" yaml:"methods,omitempty"`
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInstance) GetMethods() []*ServiceMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ApiListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApiListRequest) Reset() {
	*x = ApiListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListRequest) ProtoMessage() {}

func (x *ApiListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListRequest.ProtoReflect.Descriptor instead.
func (*ApiListRequest) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{2}
}

type ApiListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string             `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status   *ServiceStatus     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Services []*ServiceInstance `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" toml:"services,omitempty" yaml:"services,omitempty" x_attrs:"rows"`
}

func (x *ApiListResponse) Reset() {
	*x = ApiListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListResponse) ProtoMessage() {}

func (x *ApiListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListResponse.ProtoReflect.Descriptor instead.
func (*ApiListResponse) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{3}
}

func (x *ApiListResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiListResponse) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ApiListResponse) GetServices() []*ServiceInstance {
	if x != nil {
		return x.Services
	}
	return nil
}

type DataProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataProjectRequest) Reset() {
	*x = DataProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProjectRequest) ProtoMessage() {}

func (x *DataProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProjectRequest.ProtoReflect.Descriptor instead.
func (*DataProjectRequest) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{4}
}

type DataProjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      string          `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status    *ServiceStatus  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Instances []*DataInstance `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty" toml:"instances,omitempty" yaml:"instances,omitempty" x_attrs:"rows"`
}

func (x *DataProjectResponse) Reset() {
	*x = DataProjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProjectResponse) ProtoMessage() {}

func (x *DataProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProjectResponse.ProtoReflect.Descriptor instead.
func (*DataProjectResponse) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{5}
}

func (x *DataProjectResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataProjectResponse) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DataProjectResponse) GetInstances() []*DataInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string           `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" toml:"service_name,omitempty" yaml:"service_name,omitempty"`
	MethodName  string           `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty" toml:"method_name,omitempty" yaml:"method_name,omitempty"`
	Data        *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Request) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *Request) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string           `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Status *ServiceStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty" yaml:"status,omitempty"`
	Data   *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty" toml:"data,omitempty" yaml:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkapi_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_lynkapi_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_lynkapi_service_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Response) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_lynkapi_service_proto protoreflect.FileDescriptor

var file_lynkapi_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x36, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x65, 0x63, 0x22, 0x57, 0x0a, 0x0f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2e, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0xf4, 0x02, 0x0a, 0x0b, 0x4c, 0x79, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x10, 0x2e, 0x6c, 0x79,
	0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x1b, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x6c, 0x79,
	0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x12, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x1a, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x49, 0x67, 0x73, 0x65, 0x72, 0x74, 0x12, 0x13,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x1a, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x30, 0x48, 0x03, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x64,
	0x62, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x79, 0x6e,
	0x6b, 0x61, 0x70, 0x69, 0x3b, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lynkapi_service_proto_rawDescOnce sync.Once
	file_lynkapi_service_proto_rawDescData = file_lynkapi_service_proto_rawDesc
)

func file_lynkapi_service_proto_rawDescGZIP() []byte {
	file_lynkapi_service_proto_rawDescOnce.Do(func() {
		file_lynkapi_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_lynkapi_service_proto_rawDescData)
	})
	return file_lynkapi_service_proto_rawDescData
}

var file_lynkapi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lynkapi_service_proto_goTypes = []interface{}{
	(*ServiceMethod)(nil),       // 0: lynkapi.ServiceMethod
	(*ServiceInstance)(nil),     // 1: lynkapi.ServiceInstance
	(*ApiListRequest)(nil),      // 2: lynkapi.ApiListRequest
	(*ApiListResponse)(nil),     // 3: lynkapi.ApiListResponse
	(*DataProjectRequest)(nil),  // 4: lynkapi.DataProjectRequest
	(*DataProjectResponse)(nil), // 5: lynkapi.DataProjectResponse
	(*Request)(nil),             // 6: lynkapi.Request
	(*Response)(nil),            // 7: lynkapi.Response
	(*TypeSpec)(nil),            // 8: lynkapi.TypeSpec
	(*ServiceStatus)(nil),       // 9: lynkapi.ServiceStatus
	(*DataInstance)(nil),        // 10: lynkapi.DataInstance
	(*structpb.Struct)(nil),     // 11: google.protobuf.Struct
	(*DataQuery)(nil),           // 12: lynkapi.DataQuery
	(*DataInsert)(nil),          // 13: lynkapi.DataInsert
	(*DataResult)(nil),          // 14: lynkapi.DataResult
}
var file_lynkapi_service_proto_depIdxs = []int32{
	8,  // 0: lynkapi.ServiceMethod.request_spec:type_name -> lynkapi.TypeSpec
	8,  // 1: lynkapi.ServiceMethod.response_spec:type_name -> lynkapi.TypeSpec
	0,  // 2: lynkapi.ServiceInstance.methods:type_name -> lynkapi.ServiceMethod
	9,  // 3: lynkapi.ApiListResponse.status:type_name -> lynkapi.ServiceStatus
	1,  // 4: lynkapi.ApiListResponse.services:type_name -> lynkapi.ServiceInstance
	9,  // 5: lynkapi.DataProjectResponse.status:type_name -> lynkapi.ServiceStatus
	10, // 6: lynkapi.DataProjectResponse.instances:type_name -> lynkapi.DataInstance
	11, // 7: lynkapi.Request.data:type_name -> google.protobuf.Struct
	9,  // 8: lynkapi.Response.status:type_name -> lynkapi.ServiceStatus
	11, // 9: lynkapi.Response.data:type_name -> google.protobuf.Struct
	2,  // 10: lynkapi.LynkService.ApiList:input_type -> lynkapi.ApiListRequest
	6,  // 11: lynkapi.LynkService.Exec:input_type -> lynkapi.Request
	4,  // 12: lynkapi.LynkService.DataProject:input_type -> lynkapi.DataProjectRequest
	12, // 13: lynkapi.LynkService.DataQuery:input_type -> lynkapi.DataQuery
	13, // 14: lynkapi.LynkService.DataUpsert:input_type -> lynkapi.DataInsert
	13, // 15: lynkapi.LynkService.DataIgsert:input_type -> lynkapi.DataInsert
	3,  // 16: lynkapi.LynkService.ApiList:output_type -> lynkapi.ApiListResponse
	7,  // 17: lynkapi.LynkService.Exec:output_type -> lynkapi.Response
	5,  // 18: lynkapi.LynkService.DataProject:output_type -> lynkapi.DataProjectResponse
	14, // 19: lynkapi.LynkService.DataQuery:output_type -> lynkapi.DataResult
	14, // 20: lynkapi.LynkService.DataUpsert:output_type -> lynkapi.DataResult
	14, // 21: lynkapi.LynkService.DataIgsert:output_type -> lynkapi.DataResult
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_lynkapi_service_proto_init() }
func file_lynkapi_service_proto_init() {
	if File_lynkapi_service_proto != nil {
		return
	}
	file_lynkapi_type_proto_init()
	file_lynkapi_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lynkapi_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataProjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkapi_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lynkapi_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lynkapi_service_proto_goTypes,
		DependencyIndexes: file_lynkapi_service_proto_depIdxs,
		MessageInfos:      file_lynkapi_service_proto_msgTypes,
	}.Build()
	File_lynkapi_service_proto = out.File
	file_lynkapi_service_proto_rawDesc = nil
	file_lynkapi_service_proto_goTypes = nil
	file_lynkapi_service_proto_depIdxs = nil
}
